[project]
name = "ccaf-day-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anshul Keze Ubuntu", email = "avemulapalli@umass.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
ccaf-day-01 = "ccaf_day_01:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
